### ISSUE TITLE
I am getting error on Example code 

### ISSUE THREAD

**Issue by nayeeenaa** [hideakitai/IM920#1]
I am getting an error in Example program: Let me know what's wrong with me.
Below i am sharing the error details:

----------------------------

In file included from C:\Users\NAYEEN-AL-AMIN\Documents\Arduino\libraries\IM920-master/IM920.h:13:0,

                 from C:\Users\NAYEEN-AL-AMIN\Documents\Arduino\libraries\IM920-master\example\example.ino:1:

C:\Users\NAYEEN-AL-AMIN\Documents\Arduino\libraries\IM920-master/IM920/Sender.h:12:19: fatal error: cstdint: No such file or directory

 #include <cstdint>

                   ^

compilation terminated.

exit status 1
Error compiling for board Arduino/Genuino Mega or Mega 2560.

-----------------------------

**Comment by hideakitai** [comment]
Sorry, this library doesn't support avr-based Arduino yet... I will support them if I have time, thank you

**Comment by hideakitai** [comment]
@nayeeenaa Maybe latest one works. If you still want to use this library, please try it.
